### ISSUE TITLE
need a docker-compose example

### ISSUE THREAD

**Issue by edgexie** [eggjs/docker#2]
hi  I need a docker-compose example

**Comment by edgexie** [comment]
docker-compose.yml
```
version: "3"
services:
  egg:
    build:
      context: ./node
    ports:
      - 3200:7001
    volumes:
      - ./node:/home/xie/node
      - ./node/uploads:/home/xie/node/uploads
      - /home/xie/node/node_modules
    command: npm start
```
/node/Dockerfile
```
FROM node:alpine
WORKDIR /home/xie/node
COPY package.json .
RUN npm install --registry=https://registry.npm.taobao.org --production
```

notice：remove `--daemon` from npm start script
